-- =====================================================
-- Uttarakhand Next - Seed Data
-- =====================================================

-- =====================================================
-- Sample Users (Admins + Authors)
-- Password for all: "password123" (hashed)
-- =====================================================
INSERT INTO users (name, email, password_hash, bio, profession, role, is_active) VALUES
('Admin User', 'admin@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Platform administrator', 'Administrator', 'admin', TRUE),
('Rajesh Kumar', 'rajesh@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Senior journalist covering Uttarakhand news', 'Journalist', 'author', TRUE),
('Priya Sharma', 'priya@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Environmental reporter', 'Reporter', 'author', TRUE),
('Amit Singh', 'amit@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Political correspondent', 'Correspondent', 'author', TRUE);

-- =====================================================
-- Sample Articles (27 articles covering all sections and statuses)
-- =====================================================
INSERT INTO articles (author_id, title, excerpt, content, section, subsections, cover_image, status, published_at) VALUES
-- VOICES_AND_VISIONARIES (Approved)
(2, 'The Vision of a Social Entrepreneur', 'How one Uttarakhand native transformed rural villages', 'Meet Vikram Patel, a visionary social entrepreneur from Pauri Garhwal who returned to his village after a successful career in Mumbai. Over the past decade, he has transformed three villages through community-driven initiatives. His unique approach combines modern technology with traditional knowledge systems, creating sustainable livelihoods for over 500 families. Vikram believes that real development comes from within communities, not imposed from outside. His recent project on water harvesting has become a model for other regions. Today, he mentors young entrepreneurs across the state.', 'VOICES_AND_VISIONARIES', '["INSPIRATION","COMMUNITY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Women Leaders Shaping Uttarakhand Future', 'Four inspiring stories of change-makers', 'Uttarakhand is home to remarkable women leaders who are driving positive change across sectors. Deepika Singh, a former police officer, now runs an NGO supporting trafficking survivors. Asha Rawat manages a successful cooperative producing organic products. Nisha Verma leads a tech training institute for underprivileged youth. Ritu Pant founded a grassroots women''s collective focusing on environmental conservation. Each of these women faced significant challenges but persevered to create lasting impact. Their stories inspire hundreds of young women to pursue their dreams.', 'VOICES_AND_VISIONARIES', '["WOMEN","LEADERSHIP"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Youth Innovators Reimagining Rural Development', 'Next generation entrepreneurs leading change', 'A new generation of young entrepreneurs is reimagining rural development in Uttarakhand. These innovators combine traditional wisdom with modern technology to solve pressing issues. From app-based agricultural markets to renewable energy solutions, they are creating sustainable businesses. Twenty-five-year-old Arjun developed an AI-powered system for crop disease detection, helping farmers across five districts. Meanwhile, Priya created a digital platform connecting artisans directly with global buyers. These young leaders prove that development doesn''t require leaving rural areas.', 'VOICES_AND_VISIONARIES', '["YOUTH","INNOVATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- VOICES_AND_VISIONARIES (Pending)
(2, 'Grassroots Activism in Mountain Communities', 'Local movements creating systemic change', 'Grassroots activism in Uttarakhand mountain communities is achieving remarkable results without relying on top-down approaches. Community leaders are organizing around issues like water rights, forest protection, and cultural preservation. These movements are democratic, participatory, and deeply rooted in local knowledge. Unlike urban activism, mountain communities face unique challenges including isolation and limited resources. Yet their persistence has led to policy changes at the state level. This article explores how small communities are becoming powerful agents of social change. Their successes offer lessons for development work nationwide.', 'VOICES_AND_VISIONARIES', '["ACTIVISM","CHANGE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- NATURE_AND_NURTURE (Approved)
(3, 'Sacred Forests of Uttarakhand', 'Preserving biodiversity through tradition', 'Uttarakhand''s sacred forests, or "devbhoomi vans," are centuries-old conservation areas protected through religious and cultural traditions. These forests harbor remarkable biodiversity, including rare medicinal plants and endangered species. The Kedarnath Wildlife Sanctuary and Nanda Devi Biosphere Reserve are examples of how cultural values intersect with ecological preservation. Local communities have maintained these forests through generations, viewing them as temples rather than resources to exploit. Recent scientific studies confirm that sacred forests have better ecological health than many protected areas. This success model could revolutionize conservation strategies globally by integrating indigenous knowledge with modern ecology.', 'NATURE_AND_NURTURE', '["FORESTS","CONSERVATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'River Rejuvenation: Cleaning Uttarakhand''s Lifelines', 'Community efforts restore polluted waterbodies', 'Uttarakhand''s rivers, once pristine and life-giving, face severe pollution from urban runoff, industrial discharge, and agricultural waste. However, inspiring community efforts are working to rejuvenate these vital waterbodies. The Ganga Cleanup Mission involves thousands of volunteers removing plastic and waste. The Alaknanda River Association partners with local governments to monitor water quality. In Nainital, the lake restoration project has successfully reduced algal blooms through ecological engineering. These grassroots efforts demonstrate that citizen action can reverse environmental damage. Many villages are adopting zero-waste approaches to protect their water sources. The success stories prove that rivers can be healed when communities take ownership.', 'NATURE_AND_NURTURE', '["WATER","ENVIRONMENT"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(2, 'Organic Farming Revolution in the Hills', 'Transforming agriculture for sustainability', 'Uttarakhand''s organic farming movement represents a quiet revolution in sustainable agriculture. Farmers across the state are abandoning chemical inputs for traditional and organic methods. The government''s "Organic State" initiative has certified over 50,000 hectares as organic farmland. Cooperative networks help small farmers access markets and share best practices. Production of organic spices, fruits, and grains has increased significantly. Quality of soil has improved, reducing the need for expensive inputs. Farmers report higher profitability despite lower yields, as organic products command premium prices. This transformation proves that environmental sustainability and economic viability can go hand-in-hand in mountain agriculture.', 'NATURE_AND_NURTURE', '["AGRICULTURE","SUSTAINABILITY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- NATURE_AND_NURTURE (Pending)
(3, 'Wildlife Migration Corridors in Crisis', 'Preserving pathways for animal movement', 'Wildlife migration corridors in Uttarakhand face unprecedented threats from infrastructure development and habitat fragmentation. These corridors are critical for species movement, genetic diversity, and population survival. The Aravalli-Himalaya corridor and the Terai ecosystem face encroachment from roads, buildings, and agricultural expansion. Scientists warn that without action, many species will face local extinction. The Tiger Task Force has identified key corridors that need immediate protection. Conservation groups are working with villagers to create wildlife-friendly pathways. Some communities have voluntarily protected migration routes on their land. This article examines the science behind corridors and successful protection models.', 'NATURE_AND_NURTURE', '["WILDLIFE","CORRIDORS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- SPIRIT_AND_STORY (Approved)
(2, 'Ancient Temples: Guardians of Spiritual Heritage', 'Exploring sacred sites of Uttarakhand', 'Uttarakhand''s ancient temples are repositories of spiritual wisdom, architectural brilliance, and cultural identity. The Kedarnath Temple, one of the holiest Hindu pilgrimage sites, sits at 3,583 meters elevation in the Himalayas. The Badrinath Temple welcomes pilgrims from across the world. Lesser-known temples like Tungeshwar and Chopta showcase intricate stone carving traditions. These temples survived centuries of natural disasters and neglect, standing as monuments to devotion. Restoration efforts are underway to preserve their historical integrity while accommodating modern pilgrimage needs. The temples serve not just as religious centers but as cultural anchors for communities. Their architectural innovations demonstrate ancient engineering excellence that remains relevant today.', 'SPIRIT_AND_STORY', '["TEMPLES","CULTURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Folklore and Legends of the Mountains', 'Keeping oral traditions alive', 'Uttarakhand''s rich folklore comprises countless stories, legends, and oral traditions passed down through generations. These narratives encode wisdom about nature, morality, and community values. The story of Nanda Devi, the mountain goddess, reflects environmental consciousness and respect for nature. Tales of local heroes like Garhwal''s brave warriors inspire courage and sacrifice. However, urbanization and modernization threaten these oral traditions as younger generations disconnect from cultural storytelling. Several organizations are now documenting and preserving these stories through digital archives and cultural programs. School curricula increasingly include local folklore, reconnecting youth with heritage. These efforts ensure that the spiritual and philosophical wisdom embedded in mountain stories continues to guide future generations.', 'SPIRIT_AND_STORY', '["FOLKLORE","TRADITION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Festivals: Unity in Diversity', 'How celebrations bind mountain communities', 'Uttarakhand''s festivals celebrate spiritual beliefs, seasonal changes, and community bonds. The Kumaon Holi with its unique traditions differs from plains celebrations. Garhwali Bissu Festival marks the new year with color and joy. Nanda Devi Raj Jaat, held once every twelve years, is the world''s highest altitude pilgrimage. These festivals involve entire communities in preparation and celebration. They preserve cultural practices that might otherwise fade. Modern challenges including outmigration and economic pressures sometimes threaten festival celebrations. Yet communities are adapting, creating hybrid celebrations that honor tradition while accommodating modern realities. Festivals also attract tourism, providing economic benefits while spreading cultural awareness. They remain powerful tools for maintaining social cohesion and transmitting values across generations.', 'SPIRIT_AND_STORY', '["FESTIVALS","COMMUNITY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- SPIRIT_AND_STORY (Draft)
(2, 'Sacred Mythology and Environmental Wisdom', 'Deep connections between spirituality and nature', 'Uttarakhand''s sacred mythology contains profound environmental wisdom encoded in stories and spiritual beliefs. The worship of rivers, mountains, and forests reflects ecological consciousness. Mythology teaches respect for natural systems and their limits. Many rituals and practices explicitly protect biodiversity and resources. The concept of "Panchavati" (five sacred trees) guides agroforestry practices. Water sources are revered as goddesses, encouraging conservation. Animals have sacred status, limiting hunting and habitat destruction. Modern conservation science increasingly recognizes the validity of these traditional ecological practices. By reinterpreting mythology through environmental lens, communities are reconnecting spirituality with sustainability. This integration offers hope for addressing ecological crises while maintaining cultural continuity.', 'SPIRIT_AND_STORY', '["SPIRITUALITY","ECOLOGY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'draft', NULL),
-- GROWTH_AND_GRIT (Approved)
(4, 'Small Businesses: Backbone of Mountain Economy', 'Entrepreneurs driving local economic growth', 'Small and medium enterprises form the backbone of Uttarakhand''s economy, employing hundreds of thousands. From family-run hotels to artisan workshops, these businesses maintain cultural traditions while generating livelihoods. Tourism-related businesses capitalize on the state''s natural beauty and spiritual significance. Agricultural enterprises process local produce into value-added products. Handicraft businesses employ artisans and preserve traditional skills. Women entrepreneurs are particularly active, with over 30,000 registered women-owned businesses. Government support through subsidies and training programs is enabling growth. Success stories demonstrate that competitive advantages exist through quality, authenticity, and sustainability. These businesses create multiplier effects, supporting dependent industries and generating tax revenue for development.', 'GROWTH_AND_GRIT', '["BUSINESS","ENTREPRENEURSHIP"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(2, 'Resilience: Mountain People Overcoming Adversity', 'Stories of strength and perseverance', 'Mountain people of Uttarakhand embody resilience, overcoming natural disasters, economic challenges, and social pressures. The 2013 Uttarakhand floods killed thousands and displaced many more. Yet communities rebuilt with remarkable speed and determination. Avalanche zones see families maintaining livelihoods despite constant danger. Agricultural failures due to unpredictable weather are met with adaptive strategies. Migration pressures and economic hardship test community bonds, yet cultural traditions hold. Stories of individuals rebuilding after personal loss are inspiring. Young entrepreneurs persist despite limited capital and market access. This resilience doesn''t just survive; it drives innovation and adaptation. The grit of mountain people offers lessons in perseverance for the entire nation facing climate uncertainty.', 'GROWTH_AND_GRIT', '["RESILIENCE","INSPIRATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Skills and Training: Building Human Capital', 'Empowering youth for economic opportunities', 'Skill development programs are transforming lives and creating economic opportunities in Uttarakhand. Government vocational institutes train youth in hospitality, construction, and renewable energy. Private training centers specialize in IT, digital marketing, and advanced trades. Women''s collectives offer training in traditional and modern crafts. Agricultural extension programs upgrade farming techniques. These initiatives address skill gaps that employers identify as barriers to hiring. Trainees report significantly improved employment prospects and earning potential. Success rates improve when training aligns with local economic opportunities. Community participation in curriculum design ensures relevance. Scholarship programs remove financial barriers for poor students. These programs are slowly reversing youth outmigration by creating opportunities within the state.', 'GROWTH_AND_GRIT', '["SKILLS","TRAINING"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- GROWTH_AND_GRIT (Pending)
(4, 'Women''s Economic Empowerment', 'Breaking barriers, building futures', 'Women economic empowerment in Uttarakhand has accelerated through self-help groups, microfinance, and skill programs. Self-help groups mobilize collective savings and extend credit to members. Microfinance institutions provide loans to women entrepreneurs at reasonable rates. Government schemes offer subsidies for women-owned businesses. Women agricultural cooperatives improve input access and market reach. Success rates of women entrepreneurs match or exceed those of men in many sectors. However, barriers remain including limited access to capital, market information, and social acceptance. Early marriage and domestic responsibilities still limit some women''s economic participation. Programs addressing these structural barriers are showing promise. Women''s economic independence strengthens families and communities, creating multiplier benefits.', 'GROWTH_AND_GRIT', '["WOMEN","EMPOWERMENT"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- LEARNING_AND_LADDERS (Approved)
(2, 'Quality Education: Bridging the Urban-Rural Divide', 'Innovative programs bringing excellence to hill schools', 'Educational quality disparities between urban and rural Uttarakhand remain significant but are gradually narrowing. Government schools in cities offer better infrastructure and qualified teachers than remote hill villages. However, innovative initiatives are bringing quality education to underserved areas. Technology-enabled learning reaches villages lacking physical schools. Teacher training programs improve pedagogy in rural schools. Scholarship schemes remove financial barriers for poor students. Community engagement in school governance improves accountability. Public-private partnerships leverage external resources. Success stories from hill schools prove that location is not destiny; good schools can exist anywhere. Investment in rural education is critical for equitable development. As education quality improves, youth retention in villages increases.', 'LEARNING_AND_LADDERS', '["EDUCATION","QUALITY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Higher Education: Creating Opportunities', 'Universities and institutes advancing knowledge', 'Higher education institutions in Uttarakhand are expanding access while improving quality. Pandit Govind Vallabh Pant National Institute of Himalayan Studies conducts world-class research. Universities across the state offer diverse programs from agriculture to engineering. Distance education programs reach working professionals and place-bound learners. Scholarship schemes have increased enrollment from poor communities. Faculty development ensures teaching quality. Research initiatives connect academic knowledge with regional challenges. However, some argue that curricula need greater relevance to local contexts. Graduate unemployment remains a concern in some fields. Stronger industry-academia collaboration could improve employment prospects. Higher education institutions have potential to become engines of inclusive development.', 'LEARNING_AND_LADDERS', '["UNIVERSITY","RESEARCH"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Skill Development in Context of Climate Change', 'Training for green and sustainable livelihoods', 'Climate change is necessitating skill development in green technologies and sustainable practices. Renewable energy technician training prepares youth for solar and wind energy jobs. Water resource management programs address irrigation challenges. Sustainable agriculture training helps farmers adapt to changing weather patterns. Climate-resilient construction training improves building standards in disaster-prone areas. These skills align with India''s renewable energy targets and climate commitments. Graduates find employment in both government and private renewable energy projects. Training programs increasingly integrate climate adaptation with skills training. This approach ensures that livelihood improvements don''t undermine environmental sustainability. As global climate action accelerates, Uttarakhand can become a center for green skills development.', 'LEARNING_AND_LADDERS', '["SKILLS","CLIMATE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- LEARNING_AND_LADDERS (Draft)
(3, 'Digital Literacy: Bridging the Technology Divide', 'Bringing internet and tech skills to remote areas', 'Digital literacy remains a significant challenge in rural Uttarakhand despite improving internet connectivity. Elderly populations struggle with basic computer use. Limited digital skills restrict access to online services and economic opportunities. Government programs aim to provide basic digital training to all. Youth are often more digitally savvy but lack formal training in professional software. Mobile-based learning offers flexible options for busy populations. Women often lag in digital adoption due to cultural norms. Successful models train community tech ambassadors who provide peer learning. As digital services become essential for government benefits and commerce, digital literacy becomes critical. Investments in digital infrastructure and training are necessary for inclusive development.', 'LEARNING_AND_LADDERS', '["DIGITAL","LITERACY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'draft', NULL),
-- STATE_AND_STEWARDSHIP (Approved)
(2, 'Local Governance: Strengthening Panchayati Raj', 'Community participation in decision-making', 'Panchayati Raj (village governance) is the foundation of democratic participation in Uttarakhand. Gram sabhas provide forums for community members to voice concerns and participate in decisions. Women''s representation has improved through reservation policies. Transparency in financial management is increasing with digitalization. However, challenges remain including limited financial resources and dependence on state funds. Capacity building of panchayat members is ongoing but insufficient. Participation rates vary widely across regions and demographics. Communities with strong leadership demonstrate successful implementation of development projects. Technology is improving transparency and accountability. Strengthening local governance requires sustained investment in capacity building and institutional reforms. Effective panchayats become centers of development within their jurisdictions.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE","PARTICIPATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Public Health: Building Resilient Healthcare Systems', 'Ensuring wellness for all mountain communities', 'Healthcare access remains challenging in Uttarakhand''s remote and mountainous terrain. Terrain and harsh weather limit ambulance access in many areas. Urban concentration of specialist doctors leaves rural areas underserved. However, innovative solutions are improving health outcomes. ASHA workers (female health workers) bring basic healthcare to villages. Telemedicine connects remote patients with urban specialists. Government health centers provide primary care and maternal health services. Community health programs address nutrition and sanitation. Health insurance schemes remove financial barriers to treatment. Mobile health camps reach inaccessible populations. These efforts have improved childhood vaccination rates and maternal mortality indicators. Further progress requires sustained investment in rural health infrastructure and human resources.', 'STATE_AND_STEWARDSHIP', '["HEALTH","WELLNESS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Infrastructure Development: Building for the Future', 'Roads, electricity, and connectivity reaching villages', 'Infrastructure development is accelerating in Uttarakhand with improved roads, electricity, water supply, and internet connectivity. Road projects connect previously isolated villages to markets and services. Rural electrification has reached most villages; now quality and reliability need improvement. Water supply projects address drinking water shortages. Telecom infrastructure extends internet access even to remote areas. However, infrastructure quality concerns remain, with poor maintenance affecting longevity. Climate change creates new infrastructure challenges including landslide risks and flooding. Community participation in planning ensures infrastructure suits local needs. Public-private partnerships leverage resources for larger projects. Infrastructure development must balance economic benefits with environmental protection. Well-maintained infrastructure becomes foundation for broader development.', 'STATE_AND_STEWARDSHIP', '["INFRASTRUCTURE","DEVELOPMENT"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- STATE_AND_STEWARDSHIP (Pending)
(2, 'Disaster Management: Preparedness and Response', 'Building resilience to natural hazards', 'Uttarakhand faces multiple natural hazards including earthquakes, landslides, floods, and avalanches. The 2013 floods demonstrated both the destructive power of disasters and the resilience of communities. Disaster management authorities have implemented early warning systems for floods. Landslide monitoring helps identify high-risk areas. Community-based disaster management engages villages in preparedness. Training programs teach evacuation and first aid skills. Relief and rehabilitation systems aim for rapid recovery. However, preparedness remains inconsistent, with some areas better prepared than others. Climate change is increasing frequency and intensity of disasters. Disaster risk reduction must integrate environmental conservation and sustainable development. Comprehensive disaster management requires continuous investment and vigilance across all sectors.', 'STATE_AND_STEWARDSHIP', '["DISASTER","MANAGEMENT"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL);

-- =====================================================
-- Sample Article Views (for trending)
-- =====================================================
INSERT INTO article_views (article_id, views, last_viewed_at) VALUES
(1, 15420, NOW()),
(2, 12350, NOW()),
(3, 8900, NOW()),
(4, 6750, NOW()),
(5, 11200, NOW()),
(6, 9800, NOW()),
(7, 5200, NOW()),
(8, 14320, NOW()),
(9, 10650, NOW()),
(10, 8450, NOW()),
(11, 13200, NOW()),
(12, 7890, NOW()),
(13, 9340, NOW()),
(14, 6200, NOW()),
(15, 12100, NOW()),
(16, 8760, NOW()),
(17, 10340, NOW()),
(18, 7650, NOW()),
(19, 11400, NOW()),
(20, 9120, NOW()),
(21, 6890, NOW()),
(22, 13560, NOW()),
(23, 8420, NOW()),
(24, 10780, NOW()),
(25, 5340, NOW()),
(26, 12650, NOW()),
(27, 9210, NOW());
