-- =====================================================
-- Uttarakhand Next - Seed Data
-- =====================================================

-- =====================================================
-- Sample Users (Admins + Authors)
-- Password for all: "password123" (hashed)
-- =====================================================
INSERT INTO users (name, email, password_hash, bio, profession, role, is_active) VALUES
('Admin User', 'admin@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Platform administrator', 'Administrator', 'admin', TRUE),
('Rajesh Kumar', 'rajesh@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Senior journalist covering Uttarakhand news', 'Journalist', 'author', TRUE),
('Priya Sharma', 'priya@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Environmental reporter', 'Reporter', 'author', TRUE),
('Amit Singh', 'amit@uttrakhand.com', '$2b$10$hfUrQD2IYmHiuDe.3uy.v.FMaDyO.JgwqqVN5ngLDvsgyFCoocFk6', 'Political correspondent', 'Correspondent', 'author', TRUE);

-- =====================================================
-- Sample Articles (27 articles covering all sections and statuses)
-- =====================================================
INSERT INTO articles (author_id, title, excerpt, content, section, subsections, cover_image, status, published_at) VALUES
-- VOICES_AND_VISIONARIES (Approved)
(2, 'The Vision of a Social Entrepreneur', 'How one Uttarakhand native transformed rural villages', 'Meet Vikram Patel, a visionary social entrepreneur from Pauri Garhwal who returned to his village after a successful career in Mumbai. Over the past decade, he has transformed three villages through community-driven initiatives. His unique approach combines modern technology with traditional knowledge systems, creating sustainable livelihoods for over 500 families. Vikram believes that real development comes from within communities, not imposed from outside. His recent project on water harvesting has become a model for other regions. Today, he mentors young entrepreneurs across the state.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Women Leaders Shaping Uttarakhand Future', 'Four inspiring stories of change-makers', 'Uttarakhand is home to remarkable women leaders who are driving positive change across sectors. Deepika Singh, a former police officer, now runs an NGO supporting trafficking survivors. Asha Rawat manages a successful cooperative producing organic products. Nisha Verma leads a tech training institute for underprivileged youth. Ritu Pant founded a grassroots women''s collective focusing on environmental conservation. Each of these women faced significant challenges but persevered to create lasting impact. Their stories inspire hundreds of young women to pursue their dreams.', 'VOICES_AND_VISIONARIES', '["ACCOLADES"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Youth Innovators Reimagining Rural Development', 'Next generation entrepreneurs leading change', 'A new generation of young entrepreneurs is reimagining rural development in Uttarakhand. These innovators combine traditional wisdom with modern technology to solve pressing issues. From app-based agricultural markets to renewable energy solutions, they are creating sustainable businesses. Twenty-five-year-old Arjun developed an AI-powered system for crop disease detection, helping farmers across five districts. Meanwhile, Priya created a digital platform connecting artisans directly with global buyers. These young leaders prove that development doesn''t require leaving rural areas.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- VOICES_AND_VISIONARIES (Pending)
(2, 'Grassroots Activism in Mountain Communities', 'Local movements creating systemic change', 'Grassroots activism in Uttarakhand mountain communities is achieving remarkable results without relying on top-down approaches. Community leaders are organizing around issues like water rights, forest protection, and cultural preservation. These movements are democratic, participatory, and deeply rooted in local knowledge. Unlike urban activism, mountain communities face unique challenges including isolation and limited resources. Yet their persistence has led to policy changes at the state level. This article explores how small communities are becoming powerful agents of social change. Their successes offer lessons for development work nationwide.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- NATURE_AND_NURTURE (Approved)
(3, 'Sacred Forests of Uttarakhand', 'Preserving biodiversity through tradition', 'Uttarakhand''s sacred forests, or "devbhoomi vans," are centuries-old conservation areas protected through religious and cultural traditions. These forests harbor remarkable biodiversity, including rare medicinal plants and endangered species. The Kedarnath Wildlife Sanctuary and Nanda Devi Biosphere Reserve are examples of how cultural values intersect with ecological preservation. Local communities have maintained these forests through generations, viewing them as temples rather than resources to exploit. Recent scientific studies confirm that sacred forests have better ecological health than many protected areas. This success model could revolutionize conservation strategies globally by integrating indigenous knowledge with modern ecology.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'River Rejuvenation: Cleaning Uttarakhand''s Lifelines', 'Community efforts restore polluted waterbodies', 'Uttarakhand''s rivers, once pristine and life-giving, face severe pollution from urban runoff, industrial discharge, and agricultural waste. However, inspiring community efforts are working to rejuvenate these vital waterbodies. The Ganga Cleanup Mission involves thousands of volunteers removing plastic and waste. The Alaknanda River Association partners with local governments to monitor water quality. In Nainital, the lake restoration project has successfully reduced algal blooms through ecological engineering. These grassroots efforts demonstrate that citizen action can reverse environmental damage. Many villages are adopting zero-waste approaches to protect their water sources. The success stories prove that rivers can be healed when communities take ownership.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(2, 'Organic Farming Revolution in the Hills', 'Transforming agriculture for sustainability', 'Uttarakhand''s organic farming movement represents a quiet revolution in sustainable agriculture. Farmers across the state are abandoning chemical inputs for traditional and organic methods. The government''s "Organic State" initiative has certified over 50,000 hectares as organic farmland. Cooperative networks help small farmers access markets and share best practices. Production of organic spices, fruits, and grains has increased significantly. Quality of soil has improved, reducing the need for expensive inputs. Farmers report higher profitability despite lower yields, as organic products command premium prices. This transformation proves that environmental sustainability and economic viability can go hand-in-hand in mountain agriculture.', 'NATURE_AND_NURTURE', '["WELLNESS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- NATURE_AND_NURTURE (Pending)
(3, 'Wildlife Migration Corridors in Crisis', 'Preserving pathways for animal movement', 'Wildlife migration corridors in Uttarakhand face unprecedented threats from infrastructure development and habitat fragmentation. These corridors are critical for species movement, genetic diversity, and population survival. The Aravalli-Himalaya corridor and the Terai ecosystem face encroachment from roads, buildings, and agricultural expansion. Scientists warn that without action, many species will face local extinction. The Tiger Task Force has identified key corridors that need immediate protection. Conservation groups are working with villagers to create wildlife-friendly pathways. Some communities have voluntarily protected migration routes on their land. This article examines the science behind corridors and successful protection models.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- SPIRIT_AND_STORY (Approved)
(2, 'Ancient Temples: Guardians of Spiritual Heritage', 'Exploring sacred sites of Uttarakhand', 'Uttarakhand''s ancient temples are repositories of spiritual wisdom, architectural brilliance, and cultural identity. The Kedarnath Temple, one of the holiest Hindu pilgrimage sites, sits at 3,583 meters elevation in the Himalayas. The Badrinath Temple welcomes pilgrims from across the world. Lesser-known temples like Tungeshwar and Chopta showcase intricate stone carving traditions. These temples survived centuries of natural disasters and neglect, standing as monuments to devotion. Restoration efforts are underway to preserve their historical integrity while accommodating modern pilgrimage needs. The temples serve not just as religious centers but as cultural anchors for communities. Their architectural innovations demonstrate ancient engineering excellence that remains relevant today.', 'SPIRIT_AND_STORY', '["ODYSSEY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Folklore and Legends of the Mountains', 'Keeping oral traditions alive', 'Uttarakhand''s rich folklore comprises countless stories, legends, and oral traditions passed down through generations. These narratives encode wisdom about nature, morality, and community values. The story of Nanda Devi, the mountain goddess, reflects environmental consciousness and respect for nature. Tales of local heroes like Garhwal''s brave warriors inspire courage and sacrifice. However, urbanization and modernization threaten these oral traditions as younger generations disconnect from cultural storytelling. Several organizations are now documenting and preserving these stories through digital archives and cultural programs. School curricula increasingly include local folklore, reconnecting youth with heritage. These efforts ensure that the spiritual and philosophical wisdom embedded in mountain stories continues to guide future generations.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Festivals: Unity in Diversity', 'How celebrations bind mountain communities', 'Uttarakhand''s festivals celebrate spiritual beliefs, seasonal changes, and community bonds. The Kumaon Holi with its unique traditions differs from plains celebrations. Garhwali Bissu Festival marks the new year with color and joy. Nanda Devi Raj Jaat, held once every twelve years, is the world''s highest altitude pilgrimage. These festivals involve entire communities in preparation and celebration. They preserve cultural practices that might otherwise fade. Modern challenges including outmigration and economic pressures sometimes threaten festival celebrations. Yet communities are adapting, creating hybrid celebrations that honor tradition while accommodating modern realities. Festivals also attract tourism, providing economic benefits while spreading cultural awareness. They remain powerful tools for maintaining social cohesion and transmitting values across generations.', 'SPIRIT_AND_STORY', '["ODYSSEY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- SPIRIT_AND_STORY (Draft)
(2, 'Sacred Mythology and Environmental Wisdom', 'Deep connections between spirituality and nature', 'Uttarakhand''s sacred mythology contains profound environmental wisdom encoded in stories and spiritual beliefs. The worship of rivers, mountains, and forests reflects ecological consciousness. Mythology teaches respect for natural systems and their limits. Many rituals and practices explicitly protect biodiversity and resources. The concept of "Panchavati" (five sacred trees) guides agroforestry practices. Water sources are revered as goddesses, encouraging conservation. Animals have sacred status, limiting hunting and habitat destruction. Modern conservation science increasingly recognizes the validity of these traditional ecological practices. By reinterpreting mythology through environmental lens, communities are reconnecting spirituality with sustainability. This integration offers hope for addressing ecological crises while maintaining cultural continuity.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'draft', NULL),
-- GROWTH_AND_GRIT (Approved)
(4, 'Small Businesses: Backbone of Mountain Economy', 'Entrepreneurs driving local economic growth', 'Small and medium enterprises form the backbone of Uttarakhand''s economy, employing hundreds of thousands. From family-run hotels to artisan workshops, these businesses maintain cultural traditions while generating livelihoods. Tourism-related businesses capitalize on the state''s natural beauty and spiritual significance. Agricultural enterprises process local produce into value-added products. Handicraft businesses employ artisans and preserve traditional skills. Women entrepreneurs are particularly active, with over 30,000 registered women-owned businesses. Government support through subsidies and training programs is enabling growth. Success stories demonstrate that competitive advantages exist through quality, authenticity, and sustainability. These businesses create multiplier effects, supporting dependent industries and generating tax revenue for development.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(2, 'Resilience: Mountain People Overcoming Adversity', 'Stories of strength and perseverance', 'Mountain people of Uttarakhand embody resilience, overcoming natural disasters, economic challenges, and social pressures. The 2013 Uttarakhand floods killed thousands and displaced many more. Yet communities rebuilt with remarkable speed and determination. Avalanche zones see families maintaining livelihoods despite constant danger. Agricultural failures due to unpredictable weather are met with adaptive strategies. Migration pressures and economic hardship test community bonds, yet cultural traditions hold. Stories of individuals rebuilding after personal loss are inspiring. Young entrepreneurs persist despite limited capital and market access. This resilience doesn''t just survive; it drives innovation and adaptation. The grit of mountain people offers lessons in perseverance for the entire nation facing climate uncertainty.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Skills and Training: Building Human Capital', 'Empowering youth for economic opportunities', 'Skill development programs are transforming lives and creating economic opportunities in Uttarakhand. Government vocational institutes train youth in hospitality, construction, and renewable energy. Private training centers specialize in IT, digital marketing, and advanced trades. Women''s collectives offer training in traditional and modern crafts. Agricultural extension programs upgrade farming techniques. These initiatives address skill gaps that employers identify as barriers to hiring. Trainees report significantly improved employment prospects and earning potential. Success rates improve when training aligns with local economic opportunities. Community participation in curriculum design ensures relevance. Scholarship programs remove financial barriers for poor students. These programs are slowly reversing youth outmigration by creating opportunities within the state.', 'GROWTH_AND_GRIT', '["INFRATECH"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- GROWTH_AND_GRIT (Pending)
(4, 'Women''s Economic Empowerment', 'Breaking barriers, building futures', 'Women economic empowerment in Uttarakhand has accelerated through self-help groups, microfinance, and skill programs. Self-help groups mobilize collective savings and extend credit to members. Microfinance institutions provide loans to women entrepreneurs at reasonable rates. Government schemes offer subsidies for women-owned businesses. Women agricultural cooperatives improve input access and market reach. Success rates of women entrepreneurs match or exceed those of men in many sectors. However, barriers remain including limited access to capital, market information, and social acceptance. Early marriage and domestic responsibilities still limit some women''s economic participation. Programs addressing these structural barriers are showing promise. Women''s economic independence strengthens families and communities, creating multiplier benefits.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL),
-- LEARNING_AND_LADDERS (Approved)
(2, 'Quality Education: Bridging the Urban-Rural Divide', 'Innovative programs bringing excellence to hill schools', 'Educational quality disparities between urban and rural Uttarakhand remain significant but are gradually narrowing. Government schools in cities offer better infrastructure and qualified teachers than remote hill villages. However, innovative initiatives are bringing quality education to underserved areas. Technology-enabled learning reaches villages lacking physical schools. Teacher training programs improve pedagogy in rural schools. Scholarship schemes remove financial barriers for poor students. Community engagement in school governance improves accountability. Public-private partnerships leverage external resources. Success stories from hill schools prove that location is not destiny; good schools can exist anywhere. Investment in rural education is critical for equitable development. As education quality improves, youth retention in villages increases.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Higher Education: Creating Opportunities', 'Universities and institutes advancing knowledge', 'Higher education institutions in Uttarakhand are expanding access while improving quality. Pandit Govind Vallabh Pant National Institute of Himalayan Studies conducts world-class research. Universities across the state offer diverse programs from agriculture to engineering. Distance education programs reach working professionals and place-bound learners. Scholarship schemes have increased enrollment from poor communities. Faculty development ensures teaching quality. Research initiatives connect academic knowledge with regional challenges. However, some argue that curricula need greater relevance to local contexts. Graduate unemployment remains a concern in some fields. Stronger industry-academia collaboration could improve employment prospects. Higher education institutions have potential to become engines of inclusive development.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Skill Development in Context of Climate Change', 'Training for green and sustainable livelihoods', 'Climate change is necessitating skill development in green technologies and sustainable practices. Renewable energy technician training prepares youth for solar and wind energy jobs. Water resource management programs address irrigation challenges. Sustainable agriculture training helps farmers adapt to changing weather patterns. Climate-resilient construction training improves building standards in disaster-prone areas. These skills align with India''s renewable energy targets and climate commitments. Graduates find employment in both government and private renewable energy projects. Training programs increasingly integrate climate adaptation with skills training. This approach ensures that livelihood improvements don''t undermine environmental sustainability. As global climate action accelerates, Uttarakhand can become a center for green skills development.', 'LEARNING_AND_LADDERS', '["APTITUDE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- LEARNING_AND_LADDERS (Draft)
(3, 'Digital Literacy: Bridging the Technology Divide', 'Bringing internet and tech skills to remote areas', 'Digital literacy remains a significant challenge in rural Uttarakhand despite improving internet connectivity. Elderly populations struggle with basic computer use. Limited digital skills restrict access to online services and economic opportunities. Government programs aim to provide basic digital training to all. Youth are often more digitally savvy but lack formal training in professional software. Mobile-based learning offers flexible options for busy populations. Women often lag in digital adoption due to cultural norms. Successful models train community tech ambassadors who provide peer learning. As digital services become essential for government benefits and commerce, digital literacy becomes critical. Investments in digital infrastructure and training are necessary for inclusive development.', 'LEARNING_AND_LADDERS', '["INNOVATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'draft', NULL),
-- STATE_AND_STEWARDSHIP (Approved)
(2, 'Local Governance: Strengthening Panchayati Raj', 'Community participation in decision-making', 'Panchayati Raj (village governance) is the foundation of democratic participation in Uttarakhand. Gram sabhas provide forums for community members to voice concerns and participate in decisions. Women''s representation has improved through reservation policies. Transparency in financial management is increasing with digitalization. However, challenges remain including limited financial resources and dependence on state funds. Capacity building of panchayat members is ongoing but insufficient. Participation rates vary widely across regions and demographics. Communities with strong leadership demonstrate successful implementation of development projects. Technology is improving transparency and accountability. Strengthening local governance requires sustained investment in capacity building and institutional reforms. Effective panchayats become centers of development within their jurisdictions.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(4, 'Public Health: Building Resilient Healthcare Systems', 'Ensuring wellness for all mountain communities', 'Healthcare access remains challenging in Uttarakhand''s remote and mountainous terrain. Terrain and harsh weather limit ambulance access in many areas. Urban concentration of specialist doctors leaves rural areas underserved. However, innovative solutions are improving health outcomes. ASHA workers (female health workers) bring basic healthcare to villages. Telemedicine connects remote patients with urban specialists. Government health centers provide primary care and maternal health services. Community health programs address nutrition and sanitation. Health insurance schemes remove financial barriers to treatment. Mobile health camps reach inaccessible populations. These efforts have improved childhood vaccination rates and maternal mortality indicators. Further progress requires sustained investment in rural health infrastructure and human resources.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
(3, 'Infrastructure Development: Building for the Future', 'Roads, electricity, and connectivity reaching villages', 'Infrastructure development is accelerating in Uttarakhand with improved roads, electricity, water supply, and internet connectivity. Road projects connect previously isolated villages to markets and services. Rural electrification has reached most villages; now quality and reliability need improvement. Water supply projects address drinking water shortages. Telecom infrastructure extends internet access even to remote areas. However, infrastructure quality concerns remain, with poor maintenance affecting longevity. Climate change creates new infrastructure challenges including landslide risks and flooding. Community participation in planning ensures infrastructure suits local needs. Public-private partnerships leverage resources for larger projects. Infrastructure development must balance economic benefits with environmental protection. Well-maintained infrastructure becomes foundation for broader development.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),
-- STATE_AND_STEWARDSHIP (Pending)
(2, 'Disaster Management: Preparedness and Response', 'Building resilience to natural hazards', 'Uttarakhand faces multiple natural hazards including earthquakes, landslides, floods, and avalanches. The 2013 floods demonstrated both the destructive power of disasters and the resilience of communities. Disaster management authorities have implemented early warning systems for floods. Landslide monitoring helps identify high-risk areas. Community-based disaster management engages villages in preparedness. Training programs teach evacuation and first aid skills. Relief and rehabilitation systems aim for rapid recovery. However, preparedness remains inconsistent, with some areas better prepared than others. Climate change is increasing frequency and intensity of disasters. Disaster risk reduction must integrate environmental conservation and sustainable development. Comprehensive disaster management requires continuous investment and vigilance across all sectors.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'pending', NULL);

-- =====================================================
-- Additional Articles — 8 per section (all approved)
-- IDs will auto-increment from 28 onward
-- =====================================================
INSERT INTO articles (author_id, title, excerpt, content, section, subsections, cover_image, status, published_at) VALUES

-- ── VOICES_AND_VISIONARIES ──────────────────────────────────────────────────
(2, 'The Craftsman Who Built a Movement', 'How a woodcarver from Chamoli turned craft into community power', 'Ramesh Bisht grew up watching his father carve intricate wooden panels in a tiny workshop in Chamoli. Today, his cooperative employs 120 artisans across six villages, exporting to galleries in Europe and Japan. What began as an effort to save a dying craft became a full-blown social movement. Ramesh rejected offers from factories and instead built a supply chain rooted in village workshops. His model pays artisans three times the market rate and invests profits into children''s education. He says the mountain wisdom in every carving is what makes them irreplaceable. His story is proof that heritage can be an engine of economic dignity.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Breaking Barriers: A Dalit Leader''s Journey', 'From manual labour to panchayat president — one man''s fight for dignity', 'Suresh Tamta was the first Dalit to be elected panchayat president in his block of Almora district, defeating a candidate from a historically dominant caste. His win came after years of grassroots organizing, literacy drives, and relentless advocacy for drinking water in Dalit hamlets. Suresh faced social boycotts and threats but refused to step down. Today his village has a paved road, a functional anganwadi, and a self-help group for Dalit women. He credits his success to a strong network of young volunteers who believed change was possible. His story challenges assumptions about who can lead in rural Uttarakhand.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Tech Changemakers from Uttarakhand''s Hills', 'Young coders building solutions from mountain classrooms', 'A quiet revolution in tech entrepreneurship is unfolding in the hills of Uttarakhand. Young people with smartphones and shaky internet connections are building apps, bots, and platforms that solve hyper-local problems. Deepak from Pauri built a WhatsApp chatbot that helps farmers check mandi prices in real time. Kavita from Nainital created an app that translates government welfare schemes into Kumaoni. Neither of them has a computer science degree. Both learned through free online courses and village study groups. Their stories challenge the myth that innovation requires urban infrastructure. Uttarakhand''s next wave of tech leaders may be logging in from 2,000 metres above sea level.', 'VOICES_AND_VISIONARIES', '["ACCOLADES"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Stories of Migration and Return', 'Why hundreds of young Uttarakhandi professionals are coming home', 'For decades, migration has drained Uttarakhand''s villages of their most educated residents. But a quiet counter-current is building. Dozens of professionals — engineers, nurses, teachers, designers — are leaving city jobs to return home. Some are driven by the pandemic-era discovery that remote work is possible. Others want to be near ageing parents or simply crave the mountains. Meena Bisht left a marketing job in Pune to run a boutique homestay in Munsiyari. Tarun Rawat returned from Bengaluru to start an organic honey brand. These returnees are bringing skills, capital, and fresh networks. They are quietly transforming villages rather than waiting for government schemes.', 'VOICES_AND_VISIONARIES', '["DIASPORA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Women Farmers Redefining Mountain Agriculture', 'How women are taking charge of fields abandoned by migrant husbands', 'In many Uttarakhand villages, women are the de-facto farmers — their husbands having migrated to cities for wage work. What was once seen as a burden is now becoming a source of power. Women''s collectives in Pithoragarh are negotiating directly with organic produce buyers in Delhi, cutting out middlemen entirely. In Chamoli, a women''s federation has established a cold storage unit, reducing post-harvest losses by 40 percent. These women are not just surviving — they are innovating. Their deep knowledge of local varieties, soil health, and seasonal patterns is making their farms more resilient than those relying on chemical inputs. They are rewriting what it means to be a farmer in the hills.', 'VOICES_AND_VISIONARIES', '["ACCOLADES"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'The Teacher Who Transformed a Village', 'How one government school teacher became a catalyst for community change', 'When Bhawana Joshi arrived at a crumbling government school in a remote Tehri village, she found 34 students, mouldy walls, and no functioning toilet. Eight years later, the school has 210 students, a computer lab funded by alumni donations, and a vegetable garden that supplies the mid-day meal. Bhawana did not wait for government funds. She built community ownership by involving parents in school decisions and linking graduates back as mentors. Former students now sponsor scholarships for current ones. Bhawana''s approach — treating the school as a living community institution rather than a government facility — has become a case study in Uttarakhand''s education department.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Hill Youth in the Global Spotlight', 'Uttarakhand''s young athletes, artists, and scholars making India proud', 'From a mountaineer who scaled six peaks before turning 20 to a tabla player who performed at Carnegie Hall, Uttarakhand''s youth are making their mark on the world stage. Priti Negi won a national para-athletics medal despite training on a village road with no proper track. Aryan Bisht''s environmental documentary on Himalayan glaciers won an international student film award. These achievers share a common thread: a refusal to let geography be a limitation. They also share something else — mentors who believed in them before the world did. Their stories are a call for better investment in youth talent in the hills.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Silent Activists: Environmental Warriors of the Hills', 'The unsung campaigners protecting Uttarakhand''s forests and rivers', 'They do not hold press conferences or trend on social media. But the environmental activists of Uttarakhand''s village communities are among the most effective conservation agents in India. Dalli Devi, 60, has planted over 8,000 trees along a degraded ridge in Rudraprayag. The Mahila Mangal Dal of Ghansali has enforced a community ban on logging for 15 consecutive years. These activists face threats from contractors and indifference from officials. But they persist, drawing on the same spirit that drove the Chipko movement decades ago. Their work shows that the most powerful environmental protection often comes not from policy, but from people who love a particular forest, river, or mountain.', 'VOICES_AND_VISIONARIES', '["CHARISMA"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

-- ── NATURE_AND_NURTURE ──────────────────────────────────────────────────────
(4, 'Glaciers of Garhwal: A Melting Crisis', 'What Uttarakhand''s retreating glaciers mean for millions downstream', 'The Chorabari glacier, which once extended grandly down the slopes above Kedarnath, has retreated by nearly a kilometre in two decades. Scientists monitoring Uttarakhand''s 968 glaciers report that the melt rate has accelerated sharply since 2000. These glaciers are the source of the Ganga, Yamuna, and their tributaries — rivers that sustain over 400 million people. As glaciers retreat, seasonal water flows become erratic, threatening irrigation calendars that farmers have relied on for centuries. Flash floods from glacial lake outburst events have become more frequent. Uttarakhand is at the front line of a slow-moving crisis that the rest of India will soon feel far more acutely.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'The Bee Farmers of Kumaon', 'How mountain honey is becoming a global brand while saving pollinators', 'Tucked into the rhododendron forests of Kumaon, a growing number of farmers are cultivating Himalayan honeybees and marketing single-origin mountain honey to buyers across India and abroad. The wild bee population of Uttarakhand has declined sharply due to pesticide use and habitat loss. Bee farmers are fighting back by maintaining pesticide-free zones around their apiaries and lobbying village councils to adopt organic farming. Their honey commands six times the market price of commercial varieties. But the impact goes beyond profit — their apiaries are restoring pollinator populations that are critical for the forest ecosystem. A small jar of Himalayan honey carries the weight of an entire ecological restoration effort.', 'NATURE_AND_NURTURE', '["WELLNESS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'How Villages Are Fighting Landslides', 'Community science and local knowledge on the frontline of slope stability', 'Every monsoon, Uttarakhand''s hill roads are swallowed by landslides. In 2023 alone, over 200 roads were blocked for weeks, cutting off thousands of villages. But some communities are fighting back using a combination of traditional knowledge and modern geo-science. Villages in Chamoli district have revived the practice of planting native trees — particularly oak — along fragile slopes. Oak roots bind soil far more effectively than invasive pine. Community members trained by the Geological Survey of India now monitor crack patterns in slopes and issue early warnings. Their data has been integrated into the district disaster management plan. The results are measurable: villages with active slope monitoring reported fewer surprises in the 2023 monsoon than those without.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Pine Forests vs Oak Forests: A Mountain Debate', 'Why replacing chir pine with broadleaf trees matters for Uttarakhand''s water', 'Uttarakhand''s forests are at the centre of an ecological debate with enormous consequences. Decades of government plantation drives favoured chir pine — a fast-growing, commercially useful species — over the native oak and rhododendron forests they replaced. But chir pine sheds highly flammable needles, degrades soil, and does not retain water the way oak forests do. Springs and streams in pine-dominated watersheds are drying up at twice the rate of those surrounded by mixed forests. A growing coalition of scientists, forest officials, and village communities is now pushing for oak restoration. Pilot projects in Nainital show promising early results. The debate is really about what kind of forest — and what kind of future — Uttarakhand wants.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Himalayan Herbs: Nature''s Pharmacy at Risk', 'The race to protect medicinal plants before they disappear', 'The Himalayan region of Uttarakhand harbours over 1,000 known medicinal plant species, many found nowhere else on earth. Ayurvedic practitioners, pharmaceutical companies, and folk healers have depended on these plants for centuries. But overharvesting, climate shift, and habitat destruction are pushing dozens of species toward local extinction. The Brahmakamal, the state flower and a sacred herb, now blooms at higher altitudes than before — a sign of warming. Community biodiversity registers, pioneered by tribal communities in some blocks of Bageshwar, record plant locations and traditional uses, creating a baseline for conservation. Scientists warn that without active protection, several species will be functionally extinct within two decades.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Climate Refugees of the Mountains', 'The families forced to leave their villages by a changing climate', 'They are not fleeing war or political persecution — but their displacement is just as permanent. Climate refugees in Uttarakhand are leaving ancestral villages because springs have dried up, crops have failed for three consecutive years, or their homes stand on slopes too unstable to trust after repeated landslides. The state government has a relocation scheme, but it is underfunded and slow. Families who relocate struggle with identity loss and cultural disconnection. Researchers documenting these migrations warn that they represent a preview of what climate change will do to mountain communities across the Himalayas. Their stories deserve the same urgency we give to any other humanitarian crisis.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Wetlands of Uttarakhand: Hidden Treasures Under Threat', 'Why the state''s lesser-known water bodies matter more than we think', 'While the Ganga and Yamuna dominate conversation about Uttarakhand''s water, thousands of smaller wetlands — bugyals, alpine meadows, and seasonal lakes — perform equally critical ecological functions. They recharge groundwater, filter runoff, and serve as breeding grounds for amphibians and migratory birds. Many are legally unprotected and shrinking due to encroachment, drainage for agriculture, and tourism development. The Deoria Tal in Rudraprayag district attracted 80,000 visitors in 2023 — far beyond its ecological carrying capacity. Conservation groups are working with local communities to establish wetland management committees. Protecting these water bodies is not optional: they are the kidneys of the Himalayan ecosystem.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Rewilding Stories from the Terai', 'How the forests at Uttarakhand''s foothills are coming back to life', 'The Terai arc — the strip of grassland and forest running along Uttarakhand''s southern boundary — is one of India''s most important wildlife corridors. A decade of concerted conservation effort has produced remarkable results. Tiger numbers in Corbett and Rajaji have nearly doubled. Wild elephant populations are stable. Gharial crocodiles are breeding in the Ramganga. Rewilding has also brought economic opportunity: forest edge communities run nature tourism businesses that employ thousands. The challenges remain significant — human-wildlife conflict is rising as animal populations rebound — but the Terai''s recovery proves that committed conservation can reverse ecological decline within a human generation.', 'NATURE_AND_NURTURE', '["NATURE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

-- ── SPIRIT_AND_STORY ────────────────────────────────────────────────────────
(3, 'The Lost Dialects of Garhwal', 'Racing to document mountain languages before they fall silent forever', 'Linguists estimate that Uttarakhand is home to nearly two dozen distinct languages and dialects, many of them spoken by fewer than 10,000 people. Jaunsari, Rankali, Bhotia, and Chaudangsi are among the languages that could fall silent within a generation as speakers shift to Hindi and English. A team of researchers from HNB Garhwal University is conducting an emergency documentation project — recording elders, archiving folk songs, and building digital dictionaries. The loss of a language is not just a cultural tragedy; it erases irreplaceable knowledge about local ecology, astronomy, and social organisation. Several village youth are now learning their grandparents'' dialects as an act of cultural reclamation.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Mountain Music: Keeping Jaggar Alive', 'The ritualistic musical tradition that bridges the human and divine in Uttarakhand', 'Jaggar is a form of ritualistic music-drama performed during religious festivals in Kumaon and Garhwal, invoking local deities through hours-long sung narratives. Historically, every village had its own Jaggar performers. Today, the tradition survives in fewer than 200 villages, with most practitioners over 60. A cultural organisation in Nainital has begun training young musicians in the Jaggar tradition, pairing elders with teenagers in intensive apprenticeships. The first public performance by a next-generation Jaggar group drew an audience of 400 in Almora. The performers say that Jaggar is not entertainment — it is a conversation between the living and the sacred landscape. Its preservation is both a spiritual and ecological imperative.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Char Dham: Pilgrimage in the Age of Mass Tourism', 'How Uttarakhand is managing millions of pilgrims and the cost to sacred landscapes', 'In 2023, over 5.6 million pilgrims visited Uttarakhand''s Char Dham — Badrinath, Kedarnath, Gangotri, and Yamunotri. The number has tripled in a decade, driven by improved roads, government promotion, and rising spiritual tourism. The ecological cost is enormous: trails are eroded, mountain streams carry plastic, and local communities struggle with waste they lack infrastructure to manage. Temple priests and environmental activists are raising alarms. Some argue that a daily visitor cap is necessary to protect both the sacred sites and the fragile high-altitude ecosystems surrounding them. The question Uttarakhand faces is how to honour the spiritual significance of these places while the world rushes to reach them.', 'SPIRIT_AND_STORY', '["ODYSSEY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'The Artists Painting Mountain Stories', 'Uttarakhand''s visual artists keeping pictorial folk traditions alive in the digital age', 'Aipan — the intricate ritual floor and wall art of Kumaon — has adorned homes and temples for centuries, painted by women using rice paste on red clay. Today a new generation of artists is taking Aipan off the floor and onto canvas, textiles, and digital surfaces. Kamla Bisht, a 28-year-old from Almora, has 180,000 Instagram followers who follow her daily Aipan practice. She has been commissioned by hotels and apparel brands while also teaching free workshops to village girls. The tension between commercialisation and cultural integrity is real, but artists like Kamla argue that a living tradition must adapt. Aipan is no longer just ritual art — it is also a livelihood and a statement of identity.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Why Kumaoni Cuisine Is a Living Heritage', 'From bhatt ki churkani to bal mithai — food as cultural memory', 'Kumaoni cuisine is built on ingredients that grow at altitude — local lentils like bhatt and gahat, greens like ringal shoots, grains like madua. These foods are not just nutritious; they encode centuries of adaptation to mountain conditions. The recipes passed down through grandmothers carry knowledge about which foods warm the body in winter, which aid digestion at altitude, and which can be preserved through harsh months. Today, restaurateurs and food writers are beginning to document and celebrate this heritage. Some hill homestays have built their entire identity around traditional Kumaoni meals. But chefs warn that as younger generations stop cooking these dishes, the knowledge embedded in them is quietly disappearing.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Dance Forms That Tell History', 'The masked dances and harvest celebrations of Uttarakhand''s mountain communities', 'Chholia, the sword dance performed at weddings in Kumaon, is more than spectacle — it is a re-enactment of ancient martial traditions. Langvir Nritya requires performers to balance on bamboo poles 20 feet high while playing musical instruments. Jhora and Chanchari are communal circle dances that mark seasonal festivals and harvests. Each dance form carries a specific geography, community, and social meaning. Dance scholars warn that many forms are now performed only at tourist festivals, stripped of their original context. Community-based dance academies in Pithoragarh and Champawat are working to restore these forms to their original ritual and community settings, where they can breathe and evolve naturally.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Temple Architecture of Uttarakhand', 'The structural genius hidden in stone temples across the Himalayan valleys', 'The Nagara-style stone temples of Uttarakhand are marvels of engineering built without steel or concrete, yet they have survived earthquakes, avalanches, and centuries of Himalayan weather. The Lakshminarayan temple complex in Baijnath dates to the 9th century. The Kartik Swami temple on a ridgeline above Rudraprayag sits at 3,050 metres and requires a 3-km trek. These temples were not just religious centres — they were the civic, cultural, and judicial hubs of mountain communities. Structural engineers studying these buildings have found that the interlocking stone construction method dissipates seismic energy more effectively than modern techniques. Conservation architects are now applying these principles to new construction in earthquake-prone zones.', 'SPIRIT_AND_STORY', '["ODYSSEY"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Oral Poets of the High Himalayas', 'The vanishing art of extempore verse in Garhwal''s mountain villages', 'In the villages of Garhwal, there exists a tradition of oral poetry called Baramasa — twelve-month verse narratives that chronicle seasonal change, agricultural cycles, love, and longing. Master poets, known as Bazigars, compose verses on the spot, drawing from an internalised library of images, metres, and ecological observations built over decades. The best performers can sustain an improvised recital for six hours. Only a handful of such masters remain, the youngest in their fifties. A recording project by scholars from Hemwati Nandan Bahuguna University is preserving their performances. These oral poems are also ecological documents — they name plants, birds, and weather patterns that are themselves disappearing, making their preservation doubly urgent.', 'SPIRIT_AND_STORY', '["MOORINGS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

-- ── GROWTH_AND_GRIT ─────────────────────────────────────────────────────────
(2, 'Startup Dreams in the Hills', 'The entrepreneurs launching ventures from Uttarakhand''s small towns', 'Haldwani, Dehradun, and Haridwar are not obvious startup hubs. But a generation of young entrepreneurs is choosing to build their businesses here rather than relocating to metro cities. Rohit Joshi built a SaaS platform for hotel inventory management that now serves 400 properties across North India — all coded from a rented room in Haldwani. Ananya Singh runs a sustainable fashion brand from Dehradun, sourcing hand-loomed fabric from Kumaoni weavers. These founders face real challenges: limited venture capital, unreliable power, and thin talent pools. But they also have advantages — lower costs, motivated local talent, and a growing recognition that good ideas do not require a particular postal code.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'How Tourism Is Changing Hill Economies', 'The double-edged promise of adventure and spiritual tourism in Uttarakhand', 'Tourism is now Uttarakhand''s largest industry, contributing over 15 percent of state GDP. The influx of trekkers, pilgrims, and adventure tourists has created thousands of jobs — in hospitality, guiding, transport, and crafts. But the benefits are unevenly distributed. Operators and hotel chains based in cities capture most of the economic value, while local communities often work as low-wage staff. A new generation of community-based tourism enterprises is trying to change this equation. Village homestay networks, locally owned trekking companies, and community forest tourism initiatives are retaining more value within destination communities. The challenge is scaling these models while preserving the environments and cultures that attract visitors in the first place.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Migrant Workers Who Returned and Built', 'What happens when the hills'' most experienced workers come home with capital and skills', 'For a generation, Uttarakhand''s young men left for construction sites in Delhi, hotels in Mumbai, and factories in Gujarat. The remittances they sent home built cement houses and paid school fees. But a growing number are returning — not to retire, but to build. Govind Rawat came back from Dubai with savings and a certificate in electrical engineering. He now runs the only solar installation company in his block, with a team of eight. Sundar Bisht returned from Mumbai''s hotel industry to open a small restaurant in Gopeshwar that serves the kind of food urban tourists crave. These returnees are closing the loop on decades of outmigration, bringing skills and capital back to communities that need both.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Women''s Collectives Powering the Economy', 'How self-help groups became the backbone of rural finance in Uttarakhand', 'Uttarakhand has one of India''s highest densities of women''s self-help groups — over 2.5 lakh registered SHGs with membership in the millions. These groups are not just savings clubs; they are the primary source of credit for millions of rural families, operating outside formal banking in many villages. They fund children''s education, medical emergencies, and small business starts. In Almora, a federation of 340 SHGs has collectively purchased a cold storage facility, an oil press, and a packaging unit for local products. Their combined annual turnover exceeds Rs 3 crore. The SHG movement in Uttarakhand shows that financial inclusion does not require waiting for banks to reach remote villages — communities can build their own financial infrastructure.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'A Shepherd''s Billion-Rupee Dream', 'How Uttarakhand''s pastoral communities are building sustainable wool enterprises', 'The Van Gujjars and Bhotia pastoralists of Uttarakhand have migrated with their flocks across mountain pastures for centuries. Their wool — from indigenous sheep breeds adapted to altitude — is among the finest in India. For most of history, middlemen captured nearly all the value. That is beginning to change. A cooperative in Chamoli district now shears, cleans, spins, and markets its own wool directly to buyers in Bengaluru and Mumbai. The women of the cooperative are learning natural dyeing techniques, adding value at every step. Their products — blankets, shawls, and rugs — carry a QR code linking buyers to the shepherd family whose flock produced the fibre. The transparency is not just a marketing gimmick; it is an act of dignity.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Making It in Mountains: Stories of Hill Business Success', 'Entrepreneurs share what it really takes to build a business in Uttarakhand''s hills', 'Building a business in the hills means dealing with power cuts, limited logistics networks, and a talent pool that keeps migrating to cities. Yet dozens of hill entrepreneurs have built profitable, sustainable businesses without leaving. In this conversation series, five founders share the strategies that worked. A candle-maker from Lansdowne who exports to Scandinavia. A tech services firm in Srinagar Garhwal serving clients in Singapore. A dried fruit processor in Munsiyari supplying five-star hotels. Each story is different, but common threads emerge: deep local networks, patience with slow infrastructure, and a product rooted in mountain uniqueness. Their success is a manual for anyone willing to stay and build.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'The Rise of Hill Handicrafts Exports', 'How Uttarakhand''s artisans are reaching global markets without leaving their villages', 'Uttarakhand''s handicraft sector — ringal bamboo products, wool rugs, copper work, wood carving — has long been trapped in low-value local markets. A combination of e-commerce platforms and NGO-led market linkages is changing this. Artisans in Champawat are now listing their copper dhokra figurines on international craft marketplaces. A ringal craft collective in Bageshwar supplies eco-packaging to organic brands in Europe. The government''s ODOP (One District One Product) scheme has amplified some of this momentum. But artisans say the real game-changer is control over their brand story — when buyers know where and how a product was made, they are willing to pay a fair price. Mountain craft is becoming a globally recognised aesthetic.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Farmers Who Became Agri-Entrepreneurs', 'The shift from subsistence to enterprise in Uttarakhand''s agricultural communities', 'For generations, mountain farming in Uttarakhand meant growing enough to eat, with a little surplus for sale. A growing number of farmers are making the shift from subsistence to enterprise — not by abandoning traditional crops, but by adding value to them. Haldi (turmeric) grown in Gopeshwar is now sold as certified organic powder in branded packets. Apple growers in Munsiyari have formed a producer company and installed a solar-powered juice processing unit. Mandua (finger millet) from Pauri is sold as flour, cookies, and energy bars through e-commerce. These agri-entrepreneurs are not just earning more — they are making mountain farming aspirational again for young people who might otherwise have left.', 'GROWTH_AND_GRIT', '["ENDEAVOURS"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

-- ── LEARNING_AND_LADDERS ────────────────────────────────────────────────────
(4, 'Village Schools That Beat City Averages', 'How some remote government schools are outperforming urban private schools', 'In a block of Uttarkashi district, a cluster of five government schools has consistently produced district toppers for three consecutive years. Their secret is not expensive infrastructure or private tutors. It is a combination of dedicated teachers, community involvement, and a culture of academic aspiration that the school principal has spent a decade building. Parents in these villages have formed study support groups. Students from higher grades mentor those below them. The schools use locally relevant examples in maths and science — calculating water flow in irrigation channels, measuring forest plot areas — that make abstract concepts tangible. These schools challenge the assumption that quality education requires a private fee.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'The Principal Who Made a Difference', 'One woman''s mission to transform a district''s worst-performing school', 'When Sunita Rawat was posted as principal to a school in Haridwar district that had 38 percent attendance and failing board results, she did not request a transfer. She stayed for six years and transformed it into the district''s highest-performing government school. Her approach was relentless: home visits to understand why children were absent, night classes for working students, a breakfast programme funded by alumni donations, and an open-door policy that made parents feel welcome. She identified that 60 percent of absenteeism was linked to families'' need for children''s labour. By partnering with an NGO to provide a small scholarship, she eliminated this pressure. Her story is now part of a state teacher training curriculum.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Online Education in Offline Villages', 'How low-bandwidth learning is reaching Uttarakhand''s most remote communities', 'A school in a village above 2,000 metres in Pithoragarh district has internet for perhaps two hours a day, when the satellite signal is strong. Yet its students are completing online courses on programming, English communication, and data analysis. The school''s tech coordinator has set up a local server that caches course content during high-signal windows, making it available offline throughout the day. This model — sometimes called "store and forward" learning — is being replicated in 40 schools across Uttarakhand with support from a non-profit. The results show that bandwidth is not the real barrier to digital learning; creative infrastructure solutions can work even in places where the internet is more aspiration than reality.', 'LEARNING_AND_LADDERS', '["INNOVATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'IIT Dreams from Himalayan Classrooms', 'The coaching ecosystem emerging in Uttarakhand''s small towns', 'Every year, a handful of students from Uttarakhand''s rural schools crack the JEE and enter India''s elite engineering institutes. Their success is creating a visible demonstration effect. In Haldwani and Dehradun, affordable coaching centres run by IIT alumni are now preparing students who cannot afford Kota. Online mock tests, peer study groups, and teacher mentorship are filling gaps that government schools cannot. But access remains unequal — students from remote mountain blocks rarely make it to these centres. Bridge programmes that identify talent in Class 9 and provide two-year preparation support are beginning to change this. Uttarakhand has the intellectual potential to produce far more IITians than it currently does.', 'LEARNING_AND_LADDERS', '["APTITUDE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Teaching Through Stories: Hill Pedagogy', 'How culturally rooted teaching methods are improving learning outcomes in Uttarakhand', 'Educational researchers working in Uttarakhand''s schools have documented a striking pattern: students learn faster when lessons are grounded in local stories, places, and practices. A teacher in Almora who teaches fractions using traditional measurement systems for grain and cloth reports that her students outperform those taught with textbook methods. A science teacher in Tehri uses examples from local forest ecology to explain biological classification. This approach — called contextualised or culturally responsive pedagogy — is not new in academic literature, but it is rarely applied in government schools. A pilot programme in 30 Uttarakhand schools is showing promising results and is being evaluated for broader rollout.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Climate Science Enters Hill Schools', 'How Uttarakhand is building a generation of climate-aware citizens', 'A new curriculum being piloted in 50 schools across Uttarakhand''s hill districts integrates climate science into standard subjects. Students study glacier retreat in geography, calculate their village''s carbon footprint in maths, and analyse monsoon data trends in science. The programme was designed in partnership with scientists from Wadia Institute of Himalayan Geology in Dehradun. Students who complete the programme report feeling more connected to their environment and more motivated to study science. Several have presented projects at national science competitions. The curriculum also includes units on traditional ecological knowledge, so that students learn both scientific and indigenous frameworks for understanding climate. It is an education that is fully of its place.', 'LEARNING_AND_LADDERS', '["INNOVATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Libraries as Learning Centres in Remote Areas', 'How community libraries are becoming hubs of opportunity in Uttarakhand''s villages', 'A well-stocked village library with a reliable solar power connection can do what years of government programmes have struggled to achieve: make learning a daily, voluntary, joyful activity. The Himalayan Library Network has established 35 community libraries in remote blocks of Uttarakhand, each staffed by a trained village librarian. These are not just book repositories. They host reading clubs, career guidance sessions, and digital literacy workshops. In Ranikhet block, the library''s evening sessions are attended by 60 adults a week — farmers, women who never finished school, elderly residents who want to read religious texts they could never before access. The library has become the social heart of the village.', 'LEARNING_AND_LADDERS', '["EDUCATION"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Scholarships Opening Doors for Hill Youth', 'How targeted financial support is changing educational trajectories in mountain communities', 'The difference between a student from Uttarakhand''s hills reaching university and dropping out after Class 10 is often not intelligence or ambition — it is money for hostel fees, textbooks, and the bus fare to the exam centre. A growing number of alumni networks, corporate CSR programmes, and individual philanthropists are filling this gap with targeted scholarships. The Pahar Foundation supports 200 students annually from high-altitude villages. The Kumaon Alumni Trust has funded first-generation college-goers from 12 blocks of Kumaon. Recipients of these scholarships are themselves becoming donors within a decade, creating self-sustaining virtuous cycles. The return on investment of a single scholarship — measured in lives transformed, families lifted, communities energised — is among the highest of any development intervention.', 'LEARNING_AND_LADDERS', '["APTITUDE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

-- ── STATE_AND_STEWARDSHIP ───────────────────────────────────────────────────
(3, 'How One Village Became Self-Governing', 'The story of a gram sabha that stopped waiting for the state', 'The village of Dungri in Pauri Garhwal has not waited for government approvals for years. Its gram sabha meets monthly, manages a community fund of Rs 18 lakh, and has built a water treatment plant, a village guesthouse, and a solar micro-grid — all without external grants. The secret is a tradition of participatory budgeting that the current panchayat president, Leela Devi, instituted when she took office in 2016. Every household nominates priorities. The gram sabha votes. Decisions are implemented by village committees with transparent accounting. The model has attracted study visits from panchayat officials across three states. Dungri''s governance experiment proves that self-reliance is not just an aspiration — it is a practice.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'The Women Pradhans Who Changed Their Villages', 'How women elected under reservation are reshaping local governance', 'When India introduced 33 percent reservation for women in panchayat elections, sceptics predicted proxy voting — that elected women would serve as figureheads for their husbands. In Uttarakhand, the evidence tells a different story. Women pradhans in Almora, Bageshwar, and Chamoli districts have presided over villages that consistently score higher on development indicators than male-led counterparts. They prioritise water supply, school infrastructure, and sanitation — the issues that most directly affect women''s daily lives. Several women pradhans have resisted contractor corruption that their predecessors tolerated. Their governance is more transparent, more participatory, and more focused on community outcomes. The data argues for expanding, not reducing, women''s representation in local bodies.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'Water Rights Conflicts in the Hills', 'As springs dry up and pipelines fail, Uttarakhand''s villages face a governance crisis', 'Access to drinking water is becoming one of the most contested political issues in rural Uttarakhand. As natural springs dry up — scientists have documented the disappearance of over 50 percent of traditional springs in the state over 50 years — communities are increasingly dependent on government piped water schemes. These schemes are chronically under-maintained: pipes break, pumps fail, and funding is irregular. Disputes between upstream and downstream villages over water allocation are escalating. In three blocks of Tehri district, water conflicts have reached district courts. State water departments are underfunded and understaffed. Researchers argue that Uttarakhand needs a fundamental re-think of water governance, one that integrates traditional spring revival practices with modern engineering and strong local institutions.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Health Workers Walking Mountain Miles', 'The ASHA and ANM workers who are Uttarakhand''s real primary healthcare system', 'In a village 12 kilometres from the nearest road, Manju Bisht makes her rounds every Tuesday. She checks on newborns, reminds elderly residents to take their blood pressure medication, and refers complicated cases to the block health centre — which she drives them to herself when no ambulance is available. Manju is an ASHA (Accredited Social Health Activist), one of 14,000 women who form the backbone of Uttarakhand''s rural health system. They are paid piece-rates for specific services that amount to far less than minimum wage. They have no job security, no pensions, and limited training support. Yet Uttarakhand''s improvements in maternal mortality, child vaccination, and tuberculosis treatment rates are largely their achievement. Their story is one of systemic undervaluation of essential work.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Disaster-Proof Houses: A New Blueprint for the Hills', 'Engineers and communities are rethinking how buildings are constructed in earthquake-prone Uttarakhand', 'Uttarakhand sits in seismic zones IV and V — among India''s most earthquake-vulnerable regions. Most hill houses are built with locally quarried stone and minimal engineering input. A moderate earthquake can destroy them entirely. After the 2015 Nepal earthquake, engineers from IIT Roorkee began working with villages in Pithoragarh and Bageshwar to develop earthquake-resistant construction techniques using the same local stone and traditional skills. The key is improved stone bonding, diagonal bracing, and better foundations — techniques that add 15 percent to construction cost but dramatically reduce collapse risk. Several hundred families have already adopted the new techniques. The challenge is scaling adoption before the next major earthquake.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(2, 'The Auditors Who Found Missing Funds', 'How social audits are bringing accountability to MGNREGA in Uttarakhand', 'Social audits — community reviews of government programme expenditure — are mandated for MGNREGA (rural employment guarantee) work across India. In Uttarakhand, a dedicated state social audit unit has been empowering village-level social audit committees to scrutinise wage payment records, verify work completion, and identify irregularities. In 2023, social audits across the state recovered or flagged Rs 4.2 crore in questionable expenditures. The process is not without risk — audit committee members have faced pressure and threats. But many villages report that the existence of social audits has changed contractor behaviour even before an audit occurs. Accountability, it turns out, is its own deterrent.', 'STATE_AND_STEWARDSHIP', '["GOVERNANCE"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(3, 'Clean Air Policies in Mountain Towns', 'Mussoorie, Nainital, and the tourism towns facing an invisible pollution crisis', 'The tourist brochure image of Uttarakhand''s hill stations as pristine mountain retreats is under strain. Mussoorie and Nainital — two of the most visited towns — recorded PM2.5 levels above national safe limits for over 60 days in 2023. Vehicle emissions, construction dust, and waste burning are the primary contributors. The Uttarakhand Pollution Control Board is pushing for stricter vehicle emission standards and a ban on diesel generators in town centres. Nainital Municipal Council is trialling an e-rickshaw fleet to replace diesel-fuelled taxis on the town''s steep lanes. The challenge is political: tourism operators and transport unions resist restrictions that they fear will reduce visitor numbers. But the counter-argument grows stronger: polluted air is already deterring repeat visitors who came for the mountains'' clear skies.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW()),

(4, 'Village Tech Centres Bridging the Digital Divide', 'How common service centres are becoming engines of digital inclusion in Uttarakhand', 'Uttarakhand''s network of Common Service Centres (CSCs) — government-mandated digital service points — now covers almost every gram panchayat in the state. On paper. The reality is more uneven: some CSCs are dormant, their operators untrained and their equipment broken. But in villages where operators are motivated and supported, CSCs are transforming lives. In a remote block of Rudraprayag, CSC operator Dinesh Panwar processes pension applications, prints land records, conducts telemedicine consultations, and runs digital literacy classes — all from a two-room centre that serves 22 villages. His centre is a node of digital inclusion that reaches people who have never held a smartphone. Scaling this model requires investing in the human layer — training, supporting, and fairly compensating CSC operators.', 'STATE_AND_STEWARDSHIP', '["RAAG_DARBARI"]', 'https://static.vecteezy.com/system/resources/thumbnails/004/366/472/small/thumbnail-design-with-snow-mountain-background-free-vector.jpg', 'approved', NOW());

-- =====================================================
-- Sample Article Views (for trending)
-- =====================================================
INSERT INTO article_views (article_id, views, last_viewed_at) VALUES
(1, 15420, NOW()),
(2, 12350, NOW()),
(3, 8900, NOW()),
(4, 6750, NOW()),
(5, 11200, NOW()),
(6, 9800, NOW()),
(7, 5200, NOW()),
(8, 14320, NOW()),
(9, 10650, NOW()),
(10, 8450, NOW()),
(11, 13200, NOW()),
(12, 7890, NOW()),
(13, 9340, NOW()),
(14, 6200, NOW()),
(15, 12100, NOW()),
(16, 8760, NOW()),
(17, 10340, NOW()),
(18, 7650, NOW()),
(19, 11400, NOW()),
(20, 9120, NOW()),
(21, 6890, NOW()),
(22, 13560, NOW()),
(23, 8420, NOW()),
(24, 10780, NOW()),
(25, 5340, NOW()),
(26, 12650, NOW()),
(27, 9210, NOW()),
(28, 11300, NOW()),
(29, 8720, NOW()),
(30, 13100, NOW()),
(31, 7890, NOW()),
(32, 9450, NOW()),
(33, 12300, NOW()),
(34, 6780, NOW()),
(35, 10200, NOW()),
(36, 14100, NOW()),
(37, 8300, NOW()),
(38, 11900, NOW()),
(39, 7200, NOW()),
(40, 9800, NOW()),
(41, 13600, NOW()),
(42, 6500, NOW()),
(43, 10900, NOW()),
(44, 8100, NOW()),
(45, 12700, NOW()),
(46, 7400, NOW()),
(47, 9100, NOW()),
(48, 11500, NOW()),
(49, 8600, NOW()),
(50, 13400, NOW()),
(51, 7100, NOW()),
(52, 10600, NOW()),
(53, 8900, NOW()),
(54, 12100, NOW()),
(55, 6900, NOW()),
(56, 11200, NOW()),
(57, 8400, NOW()),
(58, 13800, NOW()),
(59, 7600, NOW()),
(60, 10100, NOW()),
(61, 9300, NOW()),
(62, 12500, NOW()),
(63, 7800, NOW()),
(64, 11000, NOW()),
(65, 8200, NOW()),
(66, 13200, NOW()),
(67, 6700, NOW()),
(68, 10400, NOW()),
(69, 9600, NOW()),
(70, 12900, NOW()),
(71, 7300, NOW()),
(72, 11700, NOW());
